name: Run daily build recipes manually

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 0 * * *'  # Run on 0:00 UTC 

jobs:
  run:
    runs-on: self-hosted  
    steps:
      - uses: actions/checkout@v5

      - name: Install Python 3.12 on Fedora (if missing)
        run: |
          if ! command -v python3.12 &> /dev/null; then
            sudo dnf install -y python3.12 python3.12-pip
          fi
          python3.12 --version

      - name: Use Python 3.12
        run: |
          python3.12 -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          ln -sf /usr/bin/python3.12 $HOME/python
          echo "export PATH=$HOME:$PATH" >> $GITHUB_ENV
          python3.12 -m pip install --upgrade pip
          pip install git+https://github.com/AstarVienna/ScopeSim_Templates.git
          pip install git+https://github.com/AstarVienna/ScopeSim_Data.git
          pip install git+https://github.com/AstarVienna/ScopeSim.git
          pip install astar-utils numpy more-itertools astropy PyYAML
          git clone https://github.com/AstarVienna/irdb.git # get bleeding edge version of irdb

      - name: Run recipes
        run: |
          cd Simulations
          ln -s ../irdb inst_pkgs # link to git-cloned version of irdb
          ./runESO.sh
      
      - name: Move data to /data
        run: |
          cd Simulations
          TODAY=$(date +%Y-%m-%d)
          echo "Today's date: $TODAY"
          sudo cp -rf output /data/$TODAY
          ls -la /data/$TODAY